begin;
select plan(24);
select has_table('public','grades','grades table exists');
select has_table('public','grade_change_history','grade history exists');
select has_table('public','extraordinary_evaluations','extraordinary table exists');
select has_table('public','document_versions','document versions exist');
select has_function('public','publish_assignment_grades',array['uuid','uuid','text'],'atomic publication function exists');
select has_function('public','correct_published_grade',array['uuid','grade_kind','numeric','text','integer'],'correction workflow exists');
select has_function('public','supersede_academic_document',array['uuid','text','text','text','text'],'document supersede workflow exists');
select has_function('public','revoke_academic_document',array['uuid','text'],'document revoke workflow exists');
select has_function('public','set_student_active_workflow',array['uuid','boolean','text'],'student status workflow exists');
select has_function('public','set_teacher_active_workflow',array['uuid','boolean','text'],'teacher status workflow exists');
select has_function('public','replace_teacher_assignment_workflow',array['uuid','uuid','text'],'teacher substitution workflow exists');
select has_function('public','get_my_extraordinary_overview',array[]::text[],'student extraordinary safe RPC exists');
select has_function('public','log_session_event',array['text'],'authenticated session audit RPC exists');
select col_is_unique('public','extraordinary_evaluations','student_subject_enrollment_id','one extraordinary per subject enrollment');
select policies_are('public','grades',array['grades_select'],'grades expose select only through RLS; writes are RPC-only');
select isnt_empty('select 1 from pg_class where relname=''grades'' and relrowsecurity','RLS enabled on grades');
select isnt_empty('select 1 from pg_class where relname=''audit_logs'' and relrowsecurity','RLS enabled on audit logs');
select isnt_empty('select 1 from pg_proc where proname=''verify_academic_document''','public verification RPC exists');
select isnt_empty('select 1 from pg_indexes where indexname=''document_versions_verification_token_hash_unique''','document verification token is unique per immutable version');
select isnt_empty('select 1 from pg_views where schemaname=''public'' and viewname=''student_grade_overview''','student grade overview exists');
select isnt_empty('select 1 from pg_views where schemaname=''public'' and viewname=''staff_grade_overview''','staff provisional overview exists');
select has_function('public','bootstrap_first_superadmin',array['uuid','text','text'],'service-only first Superadmin bootstrap exists');
select ok(not has_function_privilege('authenticated','public.bootstrap_first_superadmin(uuid,text,text)','EXECUTE'),'authenticated cannot execute first Superadmin bootstrap');
select ok(has_function_privilege('service_role','public.bootstrap_first_superadmin(uuid,text,text)','EXECUTE'),'service role can execute first Superadmin bootstrap');
select * from finish();
rollback;
