import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';
import QRCode from 'qrcode';

export type PartialRow={subject:string;grade:string;status:string};
export type PartialReportData={institutionName:string;studentName:string;enrollmentNumber:string;periodLabel:string;semesterLabel:string;groupName:string;partial:number;folio:string;issuedAt:Date;version:number;verificationUrl:string;rows:PartialRow[]};
type Assets={logo:Uint8Array;signature:Uint8Array;seal:Uint8Array;signatureMime:string;sealMime:string;directorName:string};
function fit(text:string,max:number){return text.length<=max?text:`${text.slice(0,Math.max(0,max-1))}…`;}
export async function generatePartialReportPdf(data:PartialReportData,assets:Assets):Promise<Uint8Array>{
  const pdf=await PDFDocument.create(),regular=await pdf.embedFont(StandardFonts.Helvetica),bold=await pdf.embedFont(StandardFonts.HelveticaBold);
  const logo=await pdf.embedPng(assets.logo),signature=assets.signatureMime.includes('png')?await pdf.embedPng(assets.signature):await pdf.embedJpg(assets.signature),seal=assets.sealMime.includes('png')?await pdf.embedPng(assets.seal):await pdf.embedJpg(assets.seal);
  const qr=await pdf.embedPng(await QRCode.toBuffer(data.verificationUrl,{type:'png',width:260,margin:1,errorCorrectionLevel:'M'}));
  const green=rgb(.21,.36,.20),yellow=rgb(.94,.72,.03),dark=rgb(.12,.16,.13),muted=rgb(.38,.43,.39),line=rgb(.82,.85,.81);
  const W=612,H=792,M=42,perPage=22;const chunks:Array<PartialRow[]>=[];for(let i=0;i<data.rows.length;i+=perPage)chunks.push(data.rows.slice(i,i+perPage));if(!chunks.length)chunks.push([]);
  chunks.forEach((rows,pageIndex)=>{const page=pdf.addPage([W,H]);page.drawRectangle({x:0,y:H-8,width:W*.72,height:8,color:green});page.drawRectangle({x:W*.72,y:H-8,width:W*.28,height:8,color:yellow});page.drawImage(logo,{x:M,y:H-96,width:64,height:64});page.drawText('CENTRO DE BACHILLERATO TECNOLOGICO AGROPECUARIO No. 241',{x:M+78,y:H-49,size:10,font:bold,color:green});page.drawText(`REPORTE OFICIAL · PARCIAL ${data.partial}`,{x:M+78,y:H-69,size:16,font:bold,color:dark});page.drawText(`${data.periodLabel} · ${data.semesterLabel} semestre · Grupo ${data.groupName}`,{x:M+78,y:H-87,size:8.5,font:regular,color:muted});let y=H-130;page.drawText('ALUMNO',{x:M,y,size:7,font:bold,color:muted});page.drawText(fit(data.studentName,58),{x:M,y:y-14,size:10,font:bold,color:dark});page.drawText('MATRICULA',{x:395,y,size:7,font:bold,color:muted});page.drawText(data.enrollmentNumber,{x:395,y:y-14,size:10,font:bold,color:dark});y-=46;page.drawRectangle({x:M,y:y-20,width:W-M*2,height:20,color:green});page.drawText('MATERIA',{x:M+6,y:y-13,size:7,font:bold,color:rgb(1,1,1)});page.drawText('CALIFICACION',{x:380,y:y-13,size:7,font:bold,color:rgb(1,1,1)});page.drawText('ESTADO',{x:475,y:y-13,size:7,font:bold,color:rgb(1,1,1)});y-=20;rows.forEach((r,i)=>{const h=23;if(i%2)page.drawRectangle({x:M,y:y-h,width:W-M*2,height:h,color:rgb(.97,.98,.96)});page.drawText(fit(r.subject,55),{x:M+6,y:y-15,size:8,font:bold,color:dark});page.drawText(r.grade,{x:400,y:y-15,size:8,font:regular,color:dark});page.drawText(fit(r.status,18),{x:475,y:y-15,size:7.2,font:regular,color:dark});page.drawLine({start:{x:M,y:y-h},end:{x:W-M,y:y-h},thickness:.3,color:line});y-=h;});if(pageIndex===chunks.length-1){y=Math.min(y-25,218);page.drawImage(signature,{x:110,y:y-4,width:105,height:45});page.drawLine({start:{x:85,y:y-10},end:{x:240,y:y-10},thickness:.6,color:muted});page.drawText(fit(assets.directorName,35),{x:90,y:y-23,size:7.5,font:bold,color:dark});page.drawText('Director(a)',{x:135,y:y-34,size:7,font:regular,color:muted});page.drawImage(seal,{x:355,y:y-25,width:78,height:78});page.drawText('Sello institucional',{x:350,y:y-37,size:7,font:regular,color:muted});page.drawImage(qr,{x:W-M-62,y:42,width:62,height:62});page.drawText('Verificacion publica',{x:W-M-75,y:30,size:6.5,font:regular,color:muted});}page.drawText(`Folio ${data.folio} · Version ${data.version} · Emitido ${data.issuedAt.toLocaleDateString('es-MX')}`,{x:M,y:20,size:6.8,font:regular,color:muted});if(chunks.length>1)page.drawText(`Pagina ${pageIndex+1} de ${chunks.length}`,{x:W-105,y:20,size:6.8,font:regular,color:muted});});return pdf.save({useObjectStreams:false});
}
