import { PageTitle } from '@/components/PageTitle';
import { createTeacherAction,setTeacherActiveAction } from '@/features/control/actions';
import { requireAuth } from '@/lib/auth/session';
import { createSupabaseServerClient } from '@/lib/supabase/server';

type Teacher={id:string;employee_number:string|null;full_name:string;is_active:boolean;profile_id:string|null};
export default async function ControlTeachers(){await requireAuth(['CONTROL_ESCOLAR']);const s=await createSupabaseServerClient();const {data:raw}=await s.from('teachers').select('id,employee_number,full_name,is_active,profile_id').order('full_name');const rows=(raw??[]) as unknown as Teacher[];return <><PageTitle eyebrow="Directorio académico" title="Docentes" description="Alta, estado operativo y trazabilidad. Desactivar un docente revoca inmediatamente su identidad académica y cierra sus asignaciones vigentes sin borrar historia."/>
<section className="section"><form action={createTeacherAction} className="login-panel document-form" style={{boxShadow:'none'}}><div className="field"><label>No. empleado</label><input aria-label="No. empleado" name="employee_number"/></div><div className="field"><label>Nombre completo</label><input aria-label="Nombre completo" name="full_name" required/></div><button className="btn btn-primary">Registrar docente</button></form></section>
<div className="flow-list">{rows.map(x=><div className="flow-row" key={x.id}><div><div className="primary">{x.full_name}</div><div className="secondary">{x.employee_number??'Sin número'} · {x.profile_id?'Cuenta vinculada':'Sin cuenta'}</div></div><div>{x.profile_id?'ACCESO VINCULADO':'PENDIENTE DE CUENTA'}</div><div><span className={`badge ${x.is_active?'badge-success':'badge-danger'}`}>{x.is_active?'ACTIVO':'INACTIVO'}</span></div><form action={setTeacherActiveAction} className="inline-action-form"><input type="hidden" name="teacher_id" value={x.id}/><input type="hidden" name="active" value={String(!x.is_active)}/><input aria-label="Motivo del cambio de estado del docente" name="reason" minLength={5} maxLength={300} placeholder="Motivo" required/><button className="btn btn-ghost">{x.is_active?'Desactivar':'Reactivar'}</button></form></div>)}</div>
{rows.length===0&&<div className="empty-state">No hay docentes registrados.</div>}</>}
